### ISSUE TITLE
Random squiggly underlines on every line

### ISSUE THREAD

**Issue by WillSewell** [serras/emacs-haskell-tutorial#24]
I set up emacs (with emacs prelude installed) in the same way as this tutorial (using the exact configuration file in this git repo). But on every line in Haskell files I get randomly positioned 1 character long squiggly underlines on every line.

Screenshot: ![Squiggly Lines](http://i.imgur.com/511ULYs.png)

Do you know what is causing this?

**Comment by serras** [comment]
This is the Haskell mode telling you the next indentation positions. If you press TAB in a line, it moves to the next squiggly-underlined position.

**Comment by WillSewell** [comment]
Ohh.. Thank you, and sorry for bothering you. Do you know if there is a way of turning this off? I find it a little distracting.

**Comment by serras** [comment]
You may try to look at the Emacs settings, under the Haskell section.

**Comment by icepolarizer** [comment]
I'm having this problem too. This is bothering the linum too! Is there any specific tweak to fix this?
