### ISSUE TITLE
Melpa vs Stable-Melpa

### ISSUE THREAD

**Issue by mortenfroelich** [serras/emacs-haskell-tutorial#30]
I just tried to follow this excellent guide to setting up a nice Haskell environment in Emacs.

I couldn't get `M-?` to work however I got the following error

~~~~
ghc-display-with-name: Symbol's function definition is void: turn-off-haskell-font-lock 
~~~~

I also got the same warning when installing the ghc package in Emacs.

From the ghc-mod github page it seems quite clear that they mainly support using stable-melpa.

Switching package repositories fixed my problem so it might be the right fix.

I am however very much an Emacs rookie so I might be going about it all wrong.

Maybe the guide should use stable-melpa?

**Comment by serras** [comment]
When the tutorial was first written, there was no stable MELPA, just a simple one. That is the reason why the tutorial mentions the unstable one.

Thanks for the advice. I have updated the tutorial with this new info :)
