### ISSUE TITLE
ghc-mod from (m)elpa has to match the cabal ghc-mod

### ISSUE THREAD

**Issue by pmiddend** [serras/emacs-haskell-tutorial#32]
I just discovered that installing ghc-mod from cabal and installing the "ghc" package via package-install is not always a good idea since both might not work together. 

I'm using ghc-mod from stackage-lts-2.9, which does not have the "legacy-interactive" command which is used by the "ghc" package from (m)elpa. So ghc-mod doesn't work for me (and, unfortunately, doesn't print a clear error message anywhere).

An alternative would be to use the .el files located in ~/.cabal/share/..., which correspond to the installed ghc-mod version. Maybe this should be advised in the tutorial?

**Comment by serras** [comment]
Thanks for reporting! I have added the information to the tutorial.
