### ISSUE TITLE
Add note about how to work with ghc-mod and 7.10

### ISSUE THREAD

**Issue by massysett** [serras/emacs-haskell-tutorial#35]
In light of this issue

https://github.com/kazu-yamamoto/ghc-mod/issues/437

could you please add a note about what to do to work with ghc-mod and GHC 7.10?  Do you just not use ghc-mod?  Stick with GHC 7.8?  Use a ghc-mod fork?  Or is it possible to compile ghc-mod with 7.8 and then use it with 7.10?

**Comment by serras** [comment]
Thanks for the information. I have added a link to the GitHub issue.
I do not know the answer to the question of what to do. I prefer to stay with GHC 7.8 until all bugs are resolved.

**Comment by massysett** [comment]
I did try compiling ghc-mod with [stack](https://github.com/commercialhaskell/stack), which will compile it with GHC 7.8.  Though I got the ghc-mod binary just fine, I could not get this binary to work with my GHC 7.10 setup.

**Comment by serras** [comment]
The way things are coded require that your `ghc-mod` to be compiled against the same version of GHC that you are using to compile your programs. If you compile `ghc-mod` with 7.8 and try to use it then with 7.10, it won't work :(
