### ISSUE TITLE
ghc-init no longer exists in the "ghc" package

### ISSUE THREAD

**Issue by martinvlk** [serras/emacs-haskell-tutorial#41]
Hi, I have been using your tutorial to setup my Haskell env in emacs and I could not find the ghc-init function to run at startup as suggested in the text.

I guess the tutorial needs to be updated to reflect changes in the ghc emacs package?

Martin

**Comment by sumitsahrawat** [comment]
The following works for me, as of today:

```lisp
(autoload 'ghc-init "ghc" nil t)
(autoload 'ghc-debug "ghc" nil t)
(add-hook 'haskell-mode-hook (lambda () (ghc-init)))
```

The same is suggested in the tutorial. Can you confirm that the `ghc` package is installed for you. Any error messages?

**Comment by martinvlk** [comment]
I have re-installed the "ghc" package, v 5.4.0.0 and now I seem to be up and running. Thanks for help, the problem was on my side, not in the tutorial.

M.
