### ISSUE TITLE
cabal install happy

### ISSUE THREAD

**Issue by mohanr** [serras/emacs-haskell-tutorial#47]
I have installed _cabal_ and when I follow the instructions I am blocked by this. Do I have to install Ghc ?

D:\Downloads>cabal update
Downloading the latest package list from hackage.haskell.org
Note: there is a new version of cabal-install available.
To upgrade, run: cabal install cabal-install

D:\Downloads>cabal install happy
cabal: The program ghc version >=6.4 is required but it could not be found.

**Comment by sumitsahrawat** [comment]
Yup, you need `ghc` for cabal to work.

**Comment by mohanr** [comment]
Done
