### ISSUE TITLE
Searching for program: no such file or directory, ghci

### ISSUE THREAD

**Issue by JasoonS** [serras/emacs-haskell-tutorial#51]
For some reason emacs is not able to find my ghci. I have no idea what the issue is. I am running Ubuntu 16.04, and followed the instructions in this tutorial to the book.

Using `which ghci` I get the path /opt/ghc/7.10.3/bin/ghci. And executing `M-: exec-path` and `M-: (getenv "PATH")` I can see that path correctly printed.

I have tried to explicitly set the PATH variable in emacs like this, which changes nothing since as far as I could tell it was already there.
`(setenv "PATH" "/usr/local/bin:/usr/bin:/bin:/opt/cabal/1.22/bin/cabal:/opt/ghc/7.10.3/bin/ghci")
(setq exec-path (split-string (getenv "PATH") path-separator)`

The same thing happens when I use 
`(custom-set-variables '(haskell-process-type 'cabal-repl))`

I would greatly appreciate help. :) I have no idea what to do, and I haven't found any answers on the internet.

**Comment by serras** [comment]
The problem is that you just need to add the folder in which `ghci` lives, not the route to `ghci` itself. That is, instead of `/opt/ghc/7.10.3/bin/ghci` just add `/opt/ghc/7.10.3/bin` to your `PATH`.

**Comment by JasoonS** [comment]
Thank you very much kind sir!! Working now :)
