### ISSUE TITLE
C-c C-r is undefined?

### ISSUE THREAD

**Issue by chrissound** [serras/emacs-haskell-tutorial#52]
Hello,

I've just tried to use the above but there is no keybinding defined for the above? I don't see it defined in the dot-emacs.el either.

**Comment by sumitsahrawat** [comment]
That's a keybinding from `HaRe`. It still uses these `C-c C-r ...` keybinds [1], but it has to be installed explicitly.

[1]: https://github.com/RefactoringTools/HaRe/blob/master/elisp/hare.el#L88-L95

**Comment by chrissound** [comment]
Cheers.
